### ISSUE TITLE
执行报错，问题反馈！

### ISSUE THREAD

**Issue by starjason** [gucong3000/free_ss#3]
执行 node free_ss.js  出现以下报错：
`/home/ubuntu/free_ss/free_ss.js:6
const srvs = {
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
`

**Comment by gucong3000** [comment]
请升级node到最新版本
https://nodejs.org/en/download/

**Comment by gucong3000** [comment]
另外`babel`可以让低版本node支持es6语法编写的js
http://babeljs.io/docs/usage/cli/
